spring:
  application:
    name: DATA-API
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/userDetails
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
